services:
  - type: web
    name: kanban-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Manually set this in Render dashboard
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    branch: main # or your default branch 